name: flutter_vali
description: "A comprehensive Flutter package for form validation and input handling, designed to simplify user input management and ensure data integrity in your applications."
version: 0.1.2
repository: https://github.com/aljaff94/flutter_vali

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
